### ISSUE TITLE
Thirstmod locks server into Peaceful Mode

### ISSUE THREAD

**Issue by PitchBright** [thetorine/thirstmod#9] opened 2015-03-08 12:12 UTC
I need to mark this bug CRITICAL, because we're dead in the water until it's fixed. I can't remove the mod from the server without borking the World file.

/difficulty 3
/gamerule doMobSpawning true
/gamerule naturalHealthRegeneration true

^ Don't work when the mod is on. The mod seems to override the server's settings and we're locked into Peaceful mode. I've tried manually editing the level.dat file to set it back, but at some point...ThirstMod overrides them again and returns it to Peaceful. (I'm assuming this is when an OP goes into Creative mode, but I haven't tested it that far yet.)

I don't know what logfile to paste to show you, but the extensive testing of removing mods one at a time from the server, and trying to set the Difficulty back to 3… doesn't work, until the very moment ThirstMod is removed. I've tried wiping the config, and reinstalling the mod… and the override takes place again. I've confirmed it 3x on my end that it's the ThirstMod.

**Comment by thetorine** [comment] 2015-03-08 12:27
Yep will put out a fix. Sorry. Disabling regeneration when the thirst is low seems to be acting up.

**Comment by thetorine** [comment] 2015-03-08 12:32
Wait you're talking about the peaceful mode being activated automatically. My mod does not touch changing the game difficulty at all. The only command above that will not work is naturalHealthRegeneration...

I'll put out an update fixing regeneration, but the game difficulty being changed is definitely not being caused by my mod. Is there any other mods that you weren't able to remove in order to test?

EDIT: Though the game difficulty being changed might be due to me changing the game rule for regeneration on a constant basis.

**Comment by PitchBright** [comment] 2015-03-08 12:38
Perhaps I mistook the naturalHealthRegen being off, as the game being set back to Peaceful. But naturalHealthRegen is being turned off, am I right?

Also, by turning Regen off because somebody's Thirst is low, that's fine for SinglePlayer… but it's not conducive to MultiPlayer.

**Comment by thetorine** [comment] 2015-03-08 12:40
"naturalHealthRegen" is turned off when the player thirst drops to zero. I couldn't find any other method to disable regeneration when the thirst was low, so I resorted to changing the game rules. I had no idea that the game rules applied to the entire world rather than just the individual player. Give me 5 minutes to release a fix. I'm so sorry about this.

**Comment by PitchBright** [comment] 2015-03-08 12:41
No problem. Thanks for jumping on this.

**Comment by thetorine** [comment] 2015-03-08 12:49
Fixed the regeneration bug and released the fix. Let me know how it goes. If it also fixes peaceful mode being locked in (if that was an problem), then please close this issue.

**Comment by thetorine** [comment] 2015-03-08 12:58
Oh sorry. You're gonna have to run the command to enable regeneration again for it to work.

**Comment by PitchBright** [comment] 2015-03-08 13:01
Okay… I'll test it now and let you know soon. Thanks again.

**Comment by thetorine** [comment] 2015-03-08 13:02
If there are any issues I won't be able to help for atleast another 16 hours..

**Comment by PitchBright** [comment] 2015-03-08 16:43
You fixed it. Thanks!

**Closed as completed** 2015-03-08 16:43 UTC
